Bootcamp at Algodaily
Shernz/Upskilling pull request #11
Opened 2022-05-17 15:38 UTC by Shernz

The day 0 problem of the Bootcamp - reverse a string.

2022-05-17 17:18 UTC, Xnkr requested changes

2022-05-17 17:18 UTC, Xnkr commented on src/com/leetcode/problem/easy/LengthOfLastWord.java
>          assert lengthOfLastWord(s[0]) == 5;
Asserts belong inside tests. Rebase and fix.

2022-05-17 17:18 UTC, Xnkr commented on src/main/java/com/algodaily/technicalInterviewPrep/ReverseAString.java
> +    public static String reverseString(String str) {
Tidbit: Explore the source of StringBuilder#reverse and other ways of reversing a string - https://explainjava.com/reverse-string-java/

2022-05-17 17:35 UTC, Xnkr commented on src/main/java/com/algodaily/technicalInterviewPrep/ReverseAString.java
> +    public static String reverseString(String str) {
You'll notice something called "[Surrogate pairs](https://stackoverflow.com/a/54922477)"

2022-05-18 14:56 UTC, Shernz commented on src/main/java/com/algodaily/technicalInterviewPrep/ReverseAString.java
> +    public static String reverseString(String str) {
In algodaily's solution, they had used recursion

2022-05-18 16:59 UTC, Xnkr commented on src/main/java/com/algodaily/technicalInterviewPrep/ReverseAString.java
> +    public static String reverseString(String str) {
O(1) space complexity

2022-05-20 06:21 UTC, Xnkr approved these changes

2022-05-20 06:21 UTC, merged