Fix/issue build tool
Shernz/Upskilling pull request #8
Opened 2022-05-11 14:39 UTC by Shernz

2022-05-14 22:22 UTC, Xnkr requested changes

2022-05-14 22:22 UTC, Xnkr commented on src/test/java/com/amazon/assessment/MinimumNetStockPriceChangeTest.java
> +        assert MinimumNetStockPriceChange.findEarliestMonth(Arrays.asList(1, 3, 2, 4, 5, 6)) == 2;
Stay consistent with the imports

Either do `import` then call static method or do `import static` then call the method

2022-05-15 09:07 UTC, Shernz commented
For some reason the code coverage is low.

2022-05-16 06:07 UTC, Xnkr approved these changes

2022-05-16 06:07 UTC, merged